= AdventOfCode 2021
:img-py: https://emojis.slackmojis.com/emojis/images/1450319444/32/python.png
:img-kt: https://emojis.slackmojis.com/emojis/images/1626243171/47442/kotlin.png
:img-sc: https://emojis.slackmojis.com/emojis/images/1489318806/1857/scala.png

== Inputs
Inputs are expected to be placed in `./inputs/year-<YYYY>/day-<DD>/` folders
_or_ `../aoc-21-inputs/year-<YYYY>/day-<DD>/`.

e.g. `./inputs/year-2021/day-01/input.txt` and `./inputs/year-2021/day-01/example.txt`

== Solutions

[cols="7*^.^^"]
|===
7+>h| 2021
h|M h|Tu h|W h|Th h|F h|Sa h|Su
||| 1 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day01.kt,16,title="Kotlin Day 1"]
image:{img-sc}[link=scala/src/main/scala/year2021/Day01.scala,16,title="Scala Day 1"]
| 2 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day02.kt,16,title="Kotlin Day 2"]
| 3 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day03.kt,16,title="Kotlin Day 3"]
| 4 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day04.kt,16,title="Kotlin Day 4"]
image:{img-py}[link=python/year-2021/day-04.py,16,title="Python Day 4"]
| 5 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day05.kt,16,title="Kotlin Day 5"]
image:{img-kt}[kotlin/src/main/kotlin/year2021/Day05Compact.kt,16,title="Kotlin Day 5 : Compact"]
image:{img-py}[link=python/year-2021/day-05.py,16,title="Python Day 5"]
| 6 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day06.kt,16,title="Kotlin Day 6"]
image:{img-py}[link=python/year-2021/day-06.py,16,title="Python Day 6"]
| 7 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day07.kt,16,title="Kotlin Day 7"]
image:{img-py}[link=python/year-2021/day-07.py,16,title="Python Day 7"]
| 8 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day08.kt,16,title="Kotlin Day 8"]
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day08Bitset.kt,width=16,title="Kotlin Day 8 : bitset"]
image:{img-py}[link=python/year-2021/day-08.py,16,title="Python Day 8"]
| 9 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day09.kt,16,title="Kotlin Day 9"]
| 10 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day10.kt,16,title="Kotlin Day 10"]
image:{img-py}[link=python/year-2021/day-10.py,16,title="Python Day 10"]
| 11 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day11.kt,16,title="Kotlin Day 11"]
image:{img-py}[link=python/year-2021/day-11.py,16,title="Python Day 11"]
| 12 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day12.kt,16,title="Kotlin Day 12"]
image:{img-py}[link=python/year-2021/day-12.py,16,title="Python Day 12"]
| 13 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day13.kt,16,title="Kotlin Day 13"]
image:{img-py}[link=python/year-2021/day-13.py,16,title="Python Day 13"]
| 14 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day14.kt,16,title="Kotlin Day 14"]
| 15 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day15.kt,16,title="Kotlin Day 15"]
image:{img-py}[link=python/year-2021/day-15.py,16,title="Python Day 15"]
| 16 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day16.kt,16,title="Kotlin Day 16"]
| 17 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day17.kt,16,title="Kotlin Day 17"]
| 18 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day18.kt,16,title="Kotlin Day 18"]
| 19 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day19.kt,16,title="Kotlin Day 19"]
| 20 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day20.kt,16,title="Kotlin Day 20"]
| 21 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day21.kt,16,title="Kotlin Day 21"]
| 22 +
image:{img-kt}[link=kotlin/src/main/kotlin/year2021/Day22.kt,16,title="Kotlin Day 22"]
| 23
| 24
| 25
| 26
| 27
| 28
| 29
| 30
| 31
||
|===
